[package]
name = "rustboy"
version = "0.3.0"
authors = ["coopersimon <simon.d.cooper@hotmail.co.uk>"]
edition = "2018"
default-run = "rustboy-bin"

[lib]
name = "rustboy"
path = "src/lib.rs"

[[bin]]
name = "rustboy-bin"
path = "src/bin/main.rs"
required-features = ["debug"]

[dependencies]
cpal = "0.11"
vulkano = "0.16"
vulkano-shaders = "0.16"
vulkano-win = "0.16"
winit = "0.19"
cgmath = "0.17"
bitflags = "1.1"
chrono = "0.4"
# Bin dependencies
clap = "2"
spin_sleep = "0.3"

[features]
debug = []

#[profile.release]
#debug = true