[package]
name = "rustboy"
version = "0.3.0"
authors = ["coopersimon <simon.d.cooper@hotmail.co.uk>"]
edition = "2018"
default-run = "rustboy-bin"

[lib]
name = "rustboy"
path = "src/lib.rs"
crate-type = ["staticlib"]

[[bin]]
name = "rustboy-bin"
path = "src/bin/main.rs"
required-features = ["debug"]

[dependencies]
cpal = "0.8"
vulkano = "0.13"
vulkano-shaders = "0.13"
vulkano-win = "0.13"
winit = "0.19"
cgmath = "0.17"
bitflags = "1.1"
clap = "2"
chrono = "0.4"

[features]
debug = []

#[profile.release]
#debug = true