[package]
name = "rustboy"
version = "0.7.0"
authors = ["coopersimon <simon.d.cooper@hotmail.co.uk>"]
edition = "2018"

[lib]
name = "rustboy"
path = "src/lib.rs"

[features]
debug = []

[dependencies]
bitflags = "1.1"
chrono = "0.4"
crossbeam-channel = "0.4.2"
